/**
 * Error codes for transmission of error reasons
 *
 */
export enum ErrorCode {
  // ERROR
  GENERAL_INTERNAL_ERROR,
  API_NOT_REACHABLE_ERROR,
  CLIENT_OFFLINE,
  GENERAL_DB_ERROR,
  WEB_SERVER_INSUFFICIENT_PERMISSIONS,
  WEB_SERVER_INVALID_CREDENTIALS,
  WEB_SERVER_INACTIVE_USER,
  WEB_SERVER_UNCALLED_RESET,
  WEB_SERVER_SUPERFLUOUS_ACTIVATION,
  WEB_SERVER_UNKNOWN_OAUTH_ERROR,
  WEB_SERVER_DUPLICATE_CREDENTIALS,
  WEB_SERVER_DUPLICATE_COMPANY,
  WEB_SERVER_INVALID_SESSION,
  WEB_SERVER_NO_ACCESS_TOKEN,
  WEB_SERVER_INVALID_SECURE_TOKEN,
  WEB_SERVER_EXPIRED_SECURE_TOKEN,
  WEB_SERVER_INVALID_USER_INPUT,
  WEB_SERVER_INVALID_DEAL,
  WEB_SERVER_COUPON_ALREADY_USED,
  WEB_SERVER_INVALID_FILE_UPLOAD,
  WEB_SERVER_INVALID_REQUEST_DATA,
  WEB_SERVER_NO_GEO_DATA_FOUND,
  WEB_SERVER_NO_DATA_FOUND,
  WEB_SERVER_INVALID_HTTP_VERB,
}
