#kind: Deployment
#apiVersion: apps/v1
#metadata:
#  name: amp-frontend-dev
#  namespace: cert-manager
#  labels:
#    app: amp
#    tier: frontend
#    version: "1"
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: amp
#      tier: frontend
#  template:
#    metadata:
#      labels:
#        app: amp
#        tier: frontend
#    spec:
#      containers:
#      - name: amp-frontend-dev
#        image: eu.gcr.io/tablespotter/amp-frontend:$COMMIT_ID
#        env:
#          - name: IS_STAGING
#            value: 'true'
#        ports:
#          - containerPort: 8080
#        livenessProbe:
#          httpGet:
#            path: /healthz
#            port: 8080
#        readinessProbe:
#          httpGet:
#            path: /healthz
#            port: 8080
#---
#kind: Service
#apiVersion: v1
#metadata:
#  name: amp-frontend-service-dev
#  namespace: cert-manager
#  labels:
#    app: amp
#    tier: frontend
#spec:
#  selector:
#    app: amp
#    tier: frontend
#  type: NodePort
#  ports:
#  - protocol: TCP
#    name: http
#    port: 80
#    targetPort: 8080
