apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencryptdns-dev
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    # Email address used for ACME registration
    email: "info@my-old-startups-domain.de"
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencryptdns-secret-dev
    # Enable the DNS-01 challenge provider
    dns01:
      providers:
        # The name given to this CloudDNS provider, multiple CloudDNS providers can be added with different names
        - name: clouddns-dev
          clouddns:
            # The ID of the GCP project
            project: my-old-startup-dev
            # This is the secret used to access the service account
            serviceAccountSecretRef:
              name: clouddns-dev
              key: clouddns.key.dev.json

#apiVersion: v1
#  kind: Secret
#  metadata:
#    name: example-tls
#    namespace: foo
#  data:
#    tls.crt: <base64 encoded cert>
#    tls.key: <base64 encoded key>
#  type: kubernetes.io/tls
